-- 판매 날짜, 상품ID, 유저ID, 판매량을 출력
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT	
-- ONLINE_SALE 테이블과 OFFLINE_SALE 테이블에서 (두개 똑같이 작성 후 UNION ALL)
FROM ONLINE_SALE
-- 2022년 3월의
WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022
-- 결과는 판매일을 기준으로 오름차순 정렬, 판매일이 같다면 상품 ID를 기준으로 오름차순, 상품ID까지 같다면 유저 ID를 기준으로 오름차순
UNION ALL

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT	
FROM OFFLINE_SALE
WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

-- UNION ALL 중복 제거 없이 합집합
