-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
SELECT A.CATEGORY, SUM(B.SALES) AS "TOTAL_SALES"
FROM BOOK A
INNER JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE LIKE "2022-01%"
GROUP BY A.CATEGORY



-- 결과는 카테고리명을 기준으로 오름차순 정렬
ORDER BY A.CATEGORY;